name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
          lfs: true

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present
        env:
          CI: true

      - run: npm run test --if-present
        env:
          CI: true
